apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  # - github.com/ansible/awx-operator/config/default?ref=2.19.1
  - github.com/ansible/awx-operator/config/manager?ref=2.19.1
  - rbac/rolebinding.yaml
  - rbac/leader_election_role_binding.yaml
  - rbac/leader_election_role.yaml
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1

# Specify a custom namespace in which to install AWX
namespace: hpv-bdmz-ota

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: awx-operator-

patches:
  - path: manager_auth_proxy_patch.yaml
