name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: test-awx-connection
        run: curl awx-demo-service.awx.svc.cluster.local:80 -v

      - name: install-ansible
        run: pip3 install ansible-core ansible-lint

      - name: test-ansible
        run: ansible -m ping localhost

      - name: trigger-awx-template
        run: curl -v awx-demo-service.awx.svc.cluster.local:80/api/v2/job_templates/7/launch/
