name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: test-awx-connection
        run: curl awx-demo-service.awx.svc.cluster.local:80 -v
